## Задача №4: Степенной метод

Ваша задача – реализовать степенной метод вычисления собственных значений и собственных векторов и протестировать его на синтетических данных. Подробности можно найти на [Википедии](https://ru.wikipedia.org/wiki/Степенной_метод).

Пожалуйста, обратите внимание, что предложенный метод должен быть применим также для вычисления наименьшего собственного значения (по абсолютной величине).

На всякий случай, для собственного значения $\lambda$ и собственного вектора $\boldsymbol{x}$ матрицы $\mathbf{A}$ справедливо следующее уравнение:
$$
\mathbf{A}\boldsymbol{x} = \lambda \boldsymbol{x}
$$

In [22]:
import numpy as np

In [34]:
a = np.random.rand(5)
data = np.random.rand(5,5)

In [35]:
a.T.dot(a)

1.2067294625316316

In [36]:
type(float(a.T.dot(data.dot(a))/a.T.dot(a))) == float

True

In [61]:
def get_dominant_eigenvalue_and_eigenvector(data, num_steps):
    """
    data: np.ndarray – symmetric diagonalizable real-valued matrix
    num_steps: int – number of power method steps

    Returns:
    eigenvalue: float – dominant eigenvalue estimation after `num_steps` steps
    eigenvector: np.ndarray – corresponding eigenvector estimation
    """
    r = np.random.rand(data.shape[0])
    for i in range(num_steps):
      r = data.dot(r)
      r /= np.linalg.norm(r)
    return float((r.T.dot(data.dot(r)))/r.T.dot(r)), r

Для вашего удобства реализовано несколько тестов ниже. В качестве корректного примера используется функция из numpy.

In [62]:

def get_eigenvalues_and_eigenvectors_with_numpy(data):
    _eigenvalues, _eigenvectors = np.linalg.eig(data)
    max_index = np.argmax(np.abs(_eigenvalues))
    min_index = np.argmin(np.abs(_eigenvalues))

    _test_pair_a = np.array([_eigenvalues[max_index], _eigenvalues[min_index]])
    _test_pair_b = np.array([_eigenvectors[:, max_index], _eigenvectors[:, min_index]])
    if _test_pair_b[0][0] < 0:
        _test_pair_b[0] *= -1
    if _test_pair_b[1][0] < 0:
        _test_pair_b[1] *= -1

    return _test_pair_a, _test_pair_b

In [63]:
for _ in range(1000):
    size = np.random.choice(np.arange(2, 5))
    data = np.random.randn(size, size)
    data = data.T.dot(data)
    a0, b0 = get_dominant_eigenvalue_and_eigenvector(data, 1000)
    assert (
        type(a0) == float
    ), "Return type for eigenvalue is not Python float (please, note, numpy.float64 is a different type)"
    assert type(b0) == np.ndarray, "Return type for eigenvector is not np.ndarray"

    a1, b1 = get_dominant_eigenvalue_and_eigenvector(np.linalg.inv(data), 1000)
    a1 = 1 / a1

    if b0[0] < 0:
        b0 *= -1
    if b1[0] < 0:
        b1 *= -1

    assert np.allclose(
        data.dot(b0), a0 * b0, atol=1e-3
    ), f"Ax != \lambda x for the dominant eigenvalue check the solution!\n{data.dot(b0), a0 * b0}"
    assert np.allclose(
        data.dot(b1), a1 * b1, atol=1e-3
    ), f"Ax != \lambda x for the smallest eigenvalue check the solution!\n{data.dot(b1), a1 * b1}"

    _test_pair_a, _test_pair_b = get_eigenvalues_and_eigenvectors_with_numpy(data)

    assert np.allclose(
        _test_pair_a, np.array([a0, a1]), atol=1e-3
    ), f"Eigenvalues are different from np.linalg.eig!\n{_test_pair_a, np.array([a0, a1])}"
    assert np.allclose(
        _test_pair_b, np.array([b0, b1]), atol=1e-3
    ), f"Eigenvectors are different from np.linalg.eig!\n{_test_pair_b, np.array([b0, b1])}"

print(
    "Seems fine! Copy function `get_dominant_eigenvalue_and_eigenvector` to the .py file and submit your solution to the contest!"
)

Seems fine! Copy function `get_dominant_eigenvalue_and_eigenvector` to the .py file and submit your solution to the contest!


In [56]:
_test_pair_b

array([[ 0.08304393, -0.85575129, -0.51067939],
       [ 0.57108713,  0.46082295, -0.67933916]])

In [57]:
b0, b1

(array([ 0.1995193 , -2.05600696, -1.22694574]),
 array([ 1.55083746,  1.25140536, -1.84480541]))